### ISSUE TITLE
Please add a license file and a readme with a screen shot

### ISSUE THREAD

**Issue by unixorn** [varunpbardwaj/bluo#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Finally, don't take these as criticisms of the work you've done, they're meant to make a more useful entry in the plugin/theme list.

Thanks!

**Comment by varunpbardwaj** [comment]
Hi @unixorn, I am glad that you noticed my work. Its my pleasure to be part of awesome-zsh-plugins. I have added Licence, Readme and gif and I am closing this thread. 

Thanks!.
